baseURL = 'https://thotran2015.github.io/portfolio018/'
locale = 'en-us'
title = 'Portfolio'
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Tho Tran'
  github = 'https://github.com/thotran2015'
  medium = 'https://medium.com/@thotran2015'
  codepen = 'https://codepen.io/dreamer1_0/'
  linkedin = 'https://www.linkedin.com/in/thotran7/'
  twitter = 'https://twitter.com/thotran2019'
  instagram = 'https://www.instagram.com/tho_tran2018/'
